# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# Run locally with: goreleaser --rm-dist --snapshot --skip-publish
project_name: g2d

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
- binary: '{{ .ProjectName }}'
  main: ./main.go
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X main.Version={{.Version}} -X main.GitCommit={{.Commit}}
    - -a -extldflags "-static"
  goos:
      - windows
      - linux
      - darwin
  goarch:
      - amd64

archives:
- replacements:
    darwin: macOS
    windows: win
    amd64: 64-bit
  files:
      - LICENSE
      - CREDITS

nfpms:
  -
    package_name: g2d
    vendor: Luca Sepe
    homepage: https://lucasepe.it/
    maintainer: Luca Sepe <luca.sepe@gmail.com>
    description: g2D Programming Language - Create beatiful drawings using an adhoc interpreted language. 
    license: MIT
    replacements:
      amd64: 64-bit
    formats:
      - deb
      - rpm

brews:
  - github:
      owner: lucasepe
      name: homebrew-g2d
    commit_author:
      name: lucasepe
      email: lucasepe@gmail.com
    homepage: 'https://github.com/lucasepe/g2d'
    description: 'Create beatiful drawings using an adhoc interpreted language'
    install: |
      bin.install "g2d"